import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';
import { ClientInquiry } from '../../client-inquiries/entities/client-inquiry.entity';

export enum ProposalStatus {
  DRAFT = 'draft',
  SENT = 'sent',
  VIEWED = 'viewed',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
  EXPIRED = 'expired',
  WITHDRAWN = 'withdrawn',
}

/**
 * Matches "proposals" from phase_1_agency_migration.sql.
 *
 * Table comment on the real schema: 'TechMate proposals sent to clients -
 * replaces marketplace-style bidding' -- same deprecation pattern as
 * client_inquiries replacing the old requests table.
 *
 * proposal_number is auto-generated by a real BEFORE INSERT trigger
 * already in the schema (generate_proposal_number(), format
 * PROP-<year>-<sequence>) -- left nullable here and re-read after insert,
 * same pattern used for Invoice.invoiceNumber/totalAmount. Do NOT
 * generate this value in the app layer; the trigger owns it and already
 * handles per-year sequencing correctly.
 *
 * status is a plain TEXT+CHECK column, not a native Postgres enum --
 * same treatment as elsewhere in this codebase.
 */
@Entity('proposals')
export class Proposal {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'varchar', name: 'inquiry_id', nullable: true })
  @Index()
  inquiryId: string | null;

  @Column({ name: 'proposal_number', unique: true, nullable: true })
  proposalNumber: string;

  @Column({ name: 'created_by' })
  createdBy: string;

  @Column()
  title: string;

  @Column({ type: 'varchar', name: 'executive_summary', nullable: true })
  executiveSummary: string | null;

  @Column({ name: 'scope_of_work' })
  scopeOfWork: string;

  @Column('jsonb', { default: () => "'[]'" })
  deliverables: unknown[];

  @Column({ name: 'timeline_weeks' })
  timelineWeeks: number;

  @Column('jsonb', { nullable: true, default: () => "'[]'" })
  milestones: unknown[] | null;

  @Column({ type: 'varchar', nullable: true })
  assumptions: string | null;

  @Column({ type: 'varchar', nullable: true })
  exclusions: string | null;

  @Column({ name: 'total_cost', type: 'numeric', precision: 12, scale: 2 })
  totalCost: number;

  @Column({ name: 'payment_schedule', type: 'jsonb', nullable: true })
  paymentSchedule: unknown[] | null;

  @Column({ type: 'varchar', name: 'payment_terms', nullable: true })
  paymentTerms: string | null;

  @Column({ default: 'USD' })
  currency: string;

  @Column({ type: 'varchar', default: ProposalStatus.DRAFT })
  @Index()
  status: ProposalStatus;

  @Column({ name: 'sent_at', type: 'timestamptz', nullable: true })
  sentAt: Date | null;

  @Column({ name: 'viewed_at', type: 'timestamptz', nullable: true })
  viewedAt: Date | null;

  @Column({ name: 'responded_at', type: 'timestamptz', nullable: true })
  respondedAt: Date | null;

  @Column({ name: 'expires_at', type: 'timestamptz', nullable: true })
  expiresAt: Date | null;

  @Column({ type: 'varchar', name: 'client_notes', nullable: true })
  clientNotes: string | null;

  @Column({ type: 'varchar', name: 'rejection_reason', nullable: true })
  rejectionReason: string | null;

  @Column({ default: 1 })
  version: number;

  @Column({ type: 'varchar', name: 'previous_version_id', nullable: true })
  previousVersionId: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @Column({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  @Index()
  deletedAt: Date | null;

  @Column('jsonb', { default: () => "'{}'" })
  metadata: Record<string, unknown>;

  @ManyToOne(() => ClientInquiry, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'inquiry_id' })
  inquiry: ClientInquiry | null;

  @ManyToOne(() => User, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'created_by' })
  creator: User;
}
